var five = 5;
var ten = 10;
console.log("\nTest1 : five is equal to five");
console.log(five == 5);
console.log("\nTest2 : ten is equal to 10");
console.log(ten == 10);
console.log("\nTest3 : five is not equal to ten");
console.log(five != ten);
console.log("\nTest4 : 10 is greater than 5");
console.log(ten > 5);
console.log("\nTest5 : 5 is smaller than 10");
console.log(five < 10);
console.log("\nTest6 : 10 is smaller than 5");
console.log(ten < 5);
console.log("\nTest7 : 5 is equal to 10");
console.log(five == ten);
console.log("\nTest8 : 10 is not equal to 10");
console.log(ten != ten);
console.log("\nTest9 : 5 is greater than 10");
console.log(five > ten);
console.log("\nTest10 : 100 is smaller than 50");
console.log(100 < 50);
